spring:
  datasource:
    url: jdbc:tc:mariadb:10.6.14://test
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        id:
          new_generator_mappings: false
  flyway:
    enabled: true
